package com.demo.dao;

import com.demo.entity.RoleFunction;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IRoleFunctionDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_function
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("roleId") Integer roleId, @Param("funcId") Integer funcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_function
     *
     * @mbg.generated
     */
    int insert(RoleFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_function
     *
     * @mbg.generated
     */
    List<RoleFunction> selectAll();
}