package com.demo.entity;


public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_roles.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_roles.role_name
     *
     * @mbg.generated
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_roles.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_roles.system
     *
     * @mbg.generated
     */
    private Boolean system;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_roles.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_roles.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_roles.update_time
     *
     * @mbg.generated
     */
    private String updateTime;
    
    private boolean flag = false;

    public boolean isFlag() {
		return flag;
	}
	public void setFlag(boolean flag) {
		this.flag = flag;
	}
	public Role(){
    	
    }
    public Role(Integer roleId, String roleName, String note, Boolean system, Integer status, String createTime,
			String updateTime) {
		super();
		this.roleId = roleId;
		this.roleName = roleName;
		this.note = note;
		this.system = system;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Override
	public String toString() {
		return "Role [roleId=" + roleId + ", roleName=" + roleName + ", note=" + note + ", system=" + system
				+ ", status=" + status + ", createTime=" + createTime + ", updateTime=" + updateTime + "]";
	}
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_roles.role_id
     *
     * @return the value of tb_roles.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_roles.role_id
     *
     * @param roleId the value for tb_roles.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_roles.role_name
     *
     * @return the value of tb_roles.role_name
     *
     * @mbg.generated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_roles.role_name
     *
     * @param roleName the value for tb_roles.role_name
     *
     * @mbg.generated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_roles.note
     *
     * @return the value of tb_roles.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_roles.note
     *
     * @param note the value for tb_roles.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_roles.system
     *
     * @return the value of tb_roles.system
     *
     * @mbg.generated
     */
    public Boolean getSystem() {
        return system;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_roles.system
     *
     * @param system the value for tb_roles.system
     *
     * @mbg.generated
     */
    public void setSystem(Boolean system) {
        this.system = system;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_roles.status
     *
     * @return the value of tb_roles.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_roles.status
     *
     * @param status the value for tb_roles.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_roles.create_time
     *
     * @return the value of tb_roles.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_roles.create_time
     *
     * @param createTime the value for tb_roles.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_roles.update_time
     *
     * @return the value of tb_roles.update_time
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_roles.update_time
     *
     * @param updateTime the value for tb_roles.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }
}